### PR TITLE
feat(simulator): transfer contractpromisebatch

### PR DESCRIPTION
**Pull request by petersalomonsen**
I need to be able to simulate transfers and inspect the receipts for transferred funds. This PR adds support for simulating ContractPromiseBatches with transfers.

### CODE REVIEW

**Comment by petersalomonsen** [comment]
@willemneal hope you find this feature as useful as I do :)

**Comment by willemneal** [comment]
Thanks for the work!  I'll go ahead and merge this since you find it useful and perhaps don't have luck with the other simulator.

**Review by willemneal — APPROVED** [review]
LGTM!

**Comment by petersalomonsen** [comment]
thanks :)

**Pull request merged**
