### PR TITLE
fix: Update as-bignum and properly expose safe integers

### PR DESCRIPTION
**Pull request by willemneal**

### CODE REVIEW

**Comment by vgrichina** [comment]
@willemneal actually after trying with bananaswap looks like the solution to export safe types doesn't work well on practice. 

Try building https://github.com/vgrichina/bananaswap/tree/master/contract with latest near-as-sdk to see what I mean. I had to downgrade explicitly to make it compile:
https://github.com/vgrichina/bananaswap/commit/1cd2a6b77522c32c6161aedbf831376984632f35#diff-cc8321d6375c494d043fdd0260f21bc0ec51dacc9f6abb7f909cdcd3041b78bf

**Comment by vgrichina** [comment]
@willemneal this kinda got off the radar, but given this PR is related I think we need to figure out how to resolve these issues. Maybe I had something wrong set up with my build.

**Comment by hdriqi** [comment]
Any update on this?

**Comment by willemneal** [comment]
@hdriqi I was about to submit a fix to as-bignum to allow for exposing the safe classes.  Still found some weird behavior with reports and "*" exports, but explicitly exporting the classes seems to work. 🤞

**Pull request merged**
