### PR TITLE
fix  validator stake typing

### LINKED ISSUE #436: Error in env.validator_stake(accountName)
**Describe the bug**
There appears to be an error in `env/env.ts#validator_stake(accountId:string)` that causes a compile-time error.

**To Reproduce**
Compile the following code with `asb`:

```ts
import {env, logging, context} from 'near-sdk-as';

export function foo():void {
  logging.log(env.validator_stake("something.near"));
}
```

The observed output is:

```sh
> sandbox@0.0.1 build:env_test
> asb assembly/env_test.ts

ERROR AS202: Type '~lib/arraybuffer/ArrayBuffer' cannot be changed to type 'u64'.

     let id_ptr = changetype<u64>(id);
                  ~~~~~~~~~~~~~~~~~~~
 in ~lib/near-sdk-core/env/env.ts(337,18)

```

**Expected behavior**
It compiles.

**Screenshots**
Issue appears to be with the unsafe`changetype<u64>`
```ts
export function validator_stake(account_id: string): u128 {
    let data = new Uint8Array(sizeof<u128>());
    let id = String.UTF8.encode(account_id);
    let id_ptr = changetype<u64>(id);
    _validator_stake(id.byteLength, id_ptr, data.dataStart);
    return u128.from(data);
  }
```

**Desktop (please complete the following information):**
 - OS: osx 11.1
 - Version: near-sdk-as 2.2.0

### PR DESCRIPTION
**Pull request by mehtaphysical**
Fixes #436 

Some minor typing issues:

* get the `id_ptr` with `changetype<usize>(id);` using `usize` instead of `u64`
* create a data `Uint8Array` with 16 bytes (128 bits). Before it used `sizeof<u128>()` which returns `usize` for a class. Change uses `offsetof`. [See here](https://www.assemblyscript.org/environment.html#sizes-and-alignments).
* change return types on the external functions

### CODE REVIEW

**Comment by mehtaphysical** [comment]
Oh I realize now that I have to apply to contribute. I'll start that.

**Comment by willemneal** [comment]
@mehtaphysical Thanks for your help!  I added more to your PR with tests, etc.

**Comment by mehtaphysical** [comment]
Thanks @willemneal ! Let me know if I can do anything to help.

ive been exploring the AssemblyScript ecosystem. You have so much awesome work there.

**Comment by mehtaphysical** [comment]
BTW, the fossa stuff is failing on this because this is coming from a fork: https://docs.fossa.com/docs/travisci#setup-your-travisci-environment

**Comment by mehtaphysical** [comment]
I don't mind closing this and make the PR come from a non-fork.

**Comment by willemneal** [comment]
@mehtaphysical Glad to have your help.  I think this is good for now, we can ignore the FOSSA check as this PR doesn't add any new dependencies anyway.

**Pull request merged**
