### PR TITLE
Add block_timestamp support

### PR DESCRIPTION
**Pull request by vgrichina**

### CODE REVIEW

**Comment by vgrichina** [comment]
@willemneal not sure what's best way to add tests for this, may you suggest?

**Comment by vgrichina** [comment]
@willemneal previously this got into such problem:

```
just try it and got error
LinkError: WebAssembly.Instance(): Import #17 module="env" function="block_timestamp" error: function import requires a callable
```

Do you know what's going on here? Is this because block_timestamp only available in newer nearcore than we have on testnet?

**Comment by willemneal** [comment]
Yeah I've also wanted to improve the way we handle imports.  Technically it shouldn't add them if you don't use them.  But perhaps we should solve that with this PR.

**Comment by vgrichina** [comment]
> Yeah I've also wanted to improve the way we handle imports. Technically it shouldn't add them if you don't use them. But perhaps we should solve that with this PR.

I just want to understand what version of nearcore is needed to actually use `block_timestamp`

**Comment by vgrichina** [comment]
@willemneal is there anything blocking the merge?

**Comment by amgando** [comment]
cherry picked into #86, closing since expecting that to merge soon with all updates

**Pull request closed without merging**
